name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cuda_version: [11.8.0]
    container:
      image: nvidia/cuda:${{ matrix.cuda_version }}-cudnn8-runtime-ubuntu22.04


    steps:
      - uses: actions/checkout@v2.1.0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            energonai:
              - 'energonai/**'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        if: steps.filter.outputs.energonai == 'true'
        run: |
          python -m pip --disable-pip-version-check install twine

      - name: Build wheels
        if: steps.filter.outputs.energonai == 'true'
        run: |
          python -m pip --disable-pip-version-check install -r requirements.txt
          python setup.py bdist_wheel
          twine check ./dist/*.whl

      - uses: actions/upload-artifact@v2
        if: steps.filter.outputs.energonai == 'true'
        with:
          name: dist
          path: ./dist/*.whl


  release:
    name: create release
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            energonai:
              - 'energonai/**'
      - name: Download artifact
        if: steps.filter.outputs.energonai == 'true'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Release
        if: steps.filter.outputs.energonai == 'true'
        # https://github.com/actions/upload-release-asset/issues/47
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs').promises;
            const { repo: { owner, repo }, sha } = context;
            console.log('environment', process.versions);
            console.log({ owner, repo, sha });
            const release = await github.repos.createRelease({
              owner, repo,
              // if GITHUB_REF just appears to be a branch, use tag-{commit} as the tag
              tag_name: process.env.GITHUB_REF.includes("refs/heads/") ? "tag-" + sha : process.env.GITHUB_REF.split("/").pop(),
              target_commitish: sha
            });
            console.log('created release', { release });
            for (let file of await fs.readdir('dist')) {
              console.log('uploading', file);
              await github.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(`./dist/${file}`)
              });
            }
      #- name: Publish distribution 📦 to Test PyPI
      #  if: steps.filter.outputs.energonai == 'true'
      #  uses: pypa/gh-action-pypi-publish@master
      #  with:
      #    verbose: true
      #    skip_existing: true
      #    verify_metadata: true
      #    user: __token__
      #    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #    repository_url: https://test.pypi.org/legacy/

      - name: Publish distribution 📦 to PyPI
        if: steps.filter.outputs.energonai == 'true'
        uses: pypa/gh-action-pypi-publish@master
        with:
          verbose: true
          skip_existing: true
          verify_metadata: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/


